import{e as a,o as t,y as n}from"./vendor.js";const l={class:"markdown-body"},p=n(`<h1>Steps \u6B65\u9AA4\u6761</h1><h3>\u4ECB\u7ECD</h3><p>\u62C6\u5206\u5C55\u793A\u67D0\u9879\u6D41\u7A0B\u7684\u6B65\u9AA4\uFF0C\u5F15\u5BFC\u7528\u6237\u6309\u6D41\u7A0B\u5B8C\u6210\u4EFB\u52A1\u6216\u5411\u7528\u6237\u5C55\u793A\u5F53\u524D\u72B6\u6001\u3002</p><h3>\u5B89\u88C5</h3><pre><code class="language-javascript"><span class="hljs-keyword">import</span> { Steps } <span class="hljs-keyword">from</span> <span class="hljs-string">&#39;@nutui/nutui-react&#39;</span>;
</code></pre><h2>\u4EE3\u7801\u6F14\u793A</h2><h3>\u57FA\u672C\u7528\u6CD5</h3><pre><code class="language-tsx">&lt;Steps current={<span class="hljs-number">1</span>}&gt;
  <span class="xml"><span class="hljs-tag">&lt;<span class="hljs-name">Step</span> <span class="hljs-attr">activeIndex</span>=<span class="hljs-string">{1}</span> <span class="hljs-attr">title</span>=<span class="hljs-string">&quot;\u6B65\u9AA4\u4E00&quot;</span>&gt;</span>1<span class="hljs-tag">&lt;/<span class="hljs-name">Step</span>&gt;</span></span>
  <span class="xml"><span class="hljs-tag">&lt;<span class="hljs-name">Step</span> <span class="hljs-attr">activeIndex</span>=<span class="hljs-string">{2}</span> <span class="hljs-attr">title</span>=<span class="hljs-string">&quot;\u6B65\u9AA4\u4E8C&quot;</span>&gt;</span>2<span class="hljs-tag">&lt;/<span class="hljs-name">Step</span>&gt;</span></span>
  <span class="xml"><span class="hljs-tag">&lt;<span class="hljs-name">Step</span> <span class="hljs-attr">activeIndex</span>=<span class="hljs-string">{3}</span> <span class="hljs-attr">title</span>=<span class="hljs-string">&quot;\u6B65\u9AA4\u4E09&quot;</span>&gt;</span>3<span class="hljs-tag">&lt;/<span class="hljs-name">Step</span>&gt;</span></span>
&lt;/Steps&gt;
</code></pre><h3>\u6807\u9898\u548C\u63CF\u8FF0\u4FE1\u606F</h3><pre><code class="language-tsx">&lt;Steps current={<span class="hljs-number">2</span>}&gt;
  <span class="xml"><span class="hljs-tag">&lt;<span class="hljs-name">Step</span> <span class="hljs-attr">activeIndex</span>=<span class="hljs-string">{1}</span> <span class="hljs-attr">title</span>=<span class="hljs-string">&quot;\u6B65\u9AA4\u4E00&quot;</span> <span class="hljs-attr">content</span>=<span class="hljs-string">&quot;\u6B65\u9AA4\u63CF\u8FF0&quot;</span>&gt;</span>1<span class="hljs-tag">&lt;/<span class="hljs-name">Step</span>&gt;</span></span>
  <span class="xml"><span class="hljs-tag">&lt;<span class="hljs-name">Step</span> <span class="hljs-attr">activeIndex</span>=<span class="hljs-string">{2}</span> <span class="hljs-attr">title</span>=<span class="hljs-string">&quot;\u6B65\u9AA4\u4E8C&quot;</span> <span class="hljs-attr">content</span>=<span class="hljs-string">&quot;\u6B65\u9AA4\u63CF\u8FF0&quot;</span>&gt;</span>2<span class="hljs-tag">&lt;/<span class="hljs-name">Step</span>&gt;</span></span>
  <span class="xml"><span class="hljs-tag">&lt;<span class="hljs-name">Step</span> <span class="hljs-attr">activeIndex</span>=<span class="hljs-string">{3}</span> <span class="hljs-attr">title</span>=<span class="hljs-string">&quot;\u6B65\u9AA4\u4E09&quot;</span> <span class="hljs-attr">content</span>=<span class="hljs-string">&quot;\u6B65\u9AA4\u63CF\u8FF0&quot;</span>&gt;</span>3<span class="hljs-tag">&lt;/<span class="hljs-name">Step</span>&gt;</span></span>
&lt;/Steps&gt;
</code></pre><h3>\u81EA\u5B9A\u4E49\u56FE\u6807</h3><pre><code class="language-tsx">&lt;Steps current={<span class="hljs-number">1</span>}&gt;
  <span class="xml"><span class="hljs-tag">&lt;<span class="hljs-name">Step</span> <span class="hljs-attr">activeIndex</span>=<span class="hljs-string">{1}</span> <span class="hljs-attr">title</span>=<span class="hljs-string">&quot;\u5DF2\u5B8C\u6210&quot;</span> <span class="hljs-attr">icon</span>=<span class="hljs-string">&quot;service&quot;</span>&gt;</span>1<span class="hljs-tag">&lt;/<span class="hljs-name">Step</span>&gt;</span></span>
  <span class="xml"><span class="hljs-tag">&lt;<span class="hljs-name">Step</span> <span class="hljs-attr">activeIndex</span>=<span class="hljs-string">{2}</span> <span class="hljs-attr">title</span>=<span class="hljs-string">&quot;\u8FDB\u884C\u4E2D&quot;</span> <span class="hljs-attr">icon</span>=<span class="hljs-string">&quot;people&quot;</span>&gt;</span>2<span class="hljs-tag">&lt;/<span class="hljs-name">Step</span>&gt;</span></span> 
  <span class="xml"><span class="hljs-tag">&lt;<span class="hljs-name">Step</span> <span class="hljs-attr">activeIndex</span>=<span class="hljs-string">{3}</span> <span class="hljs-attr">title</span>=<span class="hljs-string">&quot;\u672A\u5F00\u59CB&quot;</span> <span class="hljs-attr">icon</span>=<span class="hljs-string">&quot;location2&quot;</span>&gt;</span>3<span class="hljs-tag">&lt;/<span class="hljs-name">Step</span>&gt;</span></span>
&lt;/Steps&gt;
</code></pre><h3>\u7AD6\u5411\u6B65\u9AA4\u6761</h3><pre><code class="language-tsx">&lt;Steps direction=<span class="hljs-string">&quot;vertical&quot;</span> current={<span class="hljs-number">2</span>}&gt;
  <span class="xml"><span class="hljs-tag">&lt;<span class="hljs-name">Step</span> <span class="hljs-attr">activeIndex</span>=<span class="hljs-string">{1}</span> <span class="hljs-attr">title</span>=<span class="hljs-string">&quot;\u5DF2\u5B8C\u6210&quot;</span> <span class="hljs-attr">content</span>=<span class="hljs-string">&quot;\u60A8\u7684\u8BA2\u5355\u5DF2\u7ECF\u6253\u5305\u5B8C\u6210\uFF0C\u5546\u54C1\u5DF2\u53D1\u51FA&quot;</span>&gt;</span>1<span class="hljs-tag">&lt;/<span class="hljs-name">Step</span>&gt;</span></span>
  <span class="xml"><span class="hljs-tag">&lt;<span class="hljs-name">Step</span> <span class="hljs-attr">activeIndex</span>=<span class="hljs-string">{2}</span> <span class="hljs-attr">title</span>=<span class="hljs-string">&quot;\u8FDB\u884C\u4E2D&quot;</span> <span class="hljs-attr">content</span>=<span class="hljs-string">&quot;\u60A8\u7684\u8BA2\u5355\u6B63\u5728\u914D\u9001\u9014\u4E2D&quot;</span>&gt;</span>2<span class="hljs-tag">&lt;/<span class="hljs-name">Step</span>&gt;</span></span>
  <span class="xml"><span class="hljs-tag">&lt;<span class="hljs-name">Step</span> <span class="hljs-attr">activeIndex</span>=<span class="hljs-string">{3}</span> <span class="hljs-attr">title</span>=<span class="hljs-string">&quot;\u672A\u5F00\u59CB&quot;</span> <span class="hljs-attr">content</span>=<span class="hljs-string">&quot;\u6536\u8D27\u5730\u5740\u4E3A\uFF1A\u5317\u4EAC\u5E02\u7ECF\u6D4E\u6280\u672F\u5F00\u53D1\u533A\u79D1\u521B\u5341\u4E00\u885718\u53F7\u9662\u4EAC\u4E1C\u5927\u53A6&quot;</span>&gt;</span>3<span class="hljs-tag">&lt;/<span class="hljs-name">Step</span>&gt;</span></span>
&lt;/Steps&gt;
</code></pre><h3>\u70B9\u72B6\u6B65\u9AA4\u548C\u5782\u76F4\u65B9\u5411</h3><pre><code class="language-tsx">&lt;Steps direction=<span class="hljs-string">&quot;vertical&quot;</span> progressDot current={<span class="hljs-number">2</span>}&gt;
  <span class="xml"><span class="hljs-tag">&lt;<span class="hljs-name">Step</span> <span class="hljs-attr">activeIndex</span>=<span class="hljs-string">{1}</span> <span class="hljs-attr">title</span>=<span class="hljs-string">&quot;\u5DF2\u5B8C\u6210&quot;</span> <span class="hljs-attr">content</span>=<span class="hljs-string">&quot;\u60A8\u7684\u8BA2\u5355\u5DF2\u7ECF\u6253\u5305\u5B8C\u6210\uFF0C\u5546\u54C1\u5DF2\u53D1\u51FA&quot;</span>&gt;</span>1<span class="hljs-tag">&lt;/<span class="hljs-name">Step</span>&gt;</span></span>
  <span class="xml"><span class="hljs-tag">&lt;<span class="hljs-name">Step</span> <span class="hljs-attr">activeIndex</span>=<span class="hljs-string">{2}</span> <span class="hljs-attr">title</span>=<span class="hljs-string">&quot;\u8FDB\u884C\u4E2D&quot;</span> <span class="hljs-attr">content</span>=<span class="hljs-string">&quot;\u60A8\u7684\u8BA2\u5355\u6B63\u5728\u914D\u9001\u9014\u4E2D&quot;</span>&gt;</span>2<span class="hljs-tag">&lt;/<span class="hljs-name">Step</span>&gt;</span></span>
  <span class="xml"><span class="hljs-tag">&lt;<span class="hljs-name">Step</span> <span class="hljs-attr">activeIndex</span>=<span class="hljs-string">{3}</span> <span class="hljs-attr">title</span>=<span class="hljs-string">&quot;\u672A\u5F00\u59CB&quot;</span> <span class="hljs-attr">renderContent</span>=<span class="hljs-string">{()</span> =&gt;</span> (
        <span class="hljs-tag">&lt;&gt;</span>
            <span class="hljs-tag">&lt;<span class="hljs-name">p</span>&gt;</span>\u6536\u8D27\u5730\u5740\u4E3A\uFF1A<span class="hljs-tag">&lt;/<span class="hljs-name">p</span>&gt;</span>
            <span class="hljs-tag">&lt;<span class="hljs-name">p</span>&gt;</span>\u5317\u4EAC\u5E02\u7ECF\u6D4E\u6280\u672F\u5F00\u53D1\u533A\u79D1\u521B\u5341\u4E00\u885718\u53F7\u9662\u4EAC\u4E1C\u5927\u53A6<span class="hljs-tag">&lt;/<span class="hljs-name">p</span>&gt;</span>
        <span class="hljs-tag">&lt;/&gt;</span></span>
  )}&gt;<span class="hljs-number">3</span>&lt;/Step&gt;
&lt;/Steps&gt;
</code></pre><h2>API</h2><h3>Props</h3><h4>Steps</h4><table><thead><tr><th>\u53C2\u6570</th><th>\u8BF4\u660E</th><th>\u7C7B\u578B</th><th>\u9ED8\u8BA4\u503C</th></tr></thead><tbody><tr><td>direction</td><td>\u663E\u793A\u65B9\u5411\uFF0C<code>horizontal</code>,<code>vertical</code></td><td>String</td><td>\u2018horizontal\u2019</td></tr><tr><td>current</td><td>\u5F53\u524D\u6240\u5728\u7684\u6B65\u9AA4</td><td>Number</td><td>0</td></tr><tr><td>progressDot</td><td>\u70B9\u72B6\u6B65\u9AA4\u6761</td><td>Boolean</td><td>false</td></tr></tbody></table><h4>nut-step</h4><table><thead><tr><th>\u53C2\u6570</th><th>\u8BF4\u660E</th><th>\u7C7B\u578B</th><th>\u9ED8\u8BA4\u503C</th></tr></thead><tbody><tr><td>title</td><td>\u6D41\u7A0B\u6B65\u9AA4\u7684\u6807\u9898</td><td>String</td><td>\u2018\u2019</td></tr><tr><td>content</td><td>\u6D41\u7A0B\u6B65\u9AA4\u7684\u63CF\u8FF0\u6027\u6587\u5B57</td><td>String</td><td>\u2018\u2019</td></tr><tr><td>icon</td><td>\u56FE\u6807</td><td>String</td><td>\u2018\u2019</td></tr><tr><td>size</td><td>\u56FE\u6807\u5C3A\u5BF8\u5927\u5C0F</td><td>String</td><td>\u2018\u2019</td></tr><tr><td>activeIndex</td><td>\u6D41\u7A0B\u6B65\u9AA4\u7684\u7D22\u5F15</td><td>Number</td><td>0</td></tr><tr><td>renderContent</td><td>\u6D41\u7A0B\u6B65\u9AA4\u7684\u63CF\u8FF0\u6027\u6587\u5B57\u7684html\u7ED3\u6784</td><td>React.ReactNode</td><td>-</td></tr></tbody></table>`,22),c=[p],o={setup(e,{expose:s}){return s({frontmatter:{}}),(r,j)=>(t(),a("div",l,c))}};export{o as default};
