import{e as a,o as t,y as n}from"./vendor.js";const l={class:"markdown-body"},p=n(`<h1>Tabbar \u6807\u7B7E\u680F</h1><h3>\u4ECB\u7ECD</h3><p>\u5E95\u90E8\u5BFC\u822A\u5E38\u7528\u573A\u666F</p><h3>\u5B89\u88C5</h3><pre><code class="language-javascript"><span class="hljs-keyword">import</span> { Tabbar } <span class="hljs-keyword">from</span> <span class="hljs-string">&#39;@nutui/nutui-react&#39;</span>;
</code></pre><h2>\u4EE3\u7801\u6F14\u793A</h2><h3>\u57FA\u7840\u7528\u6CD5</h3><pre><code class="language-tsx">&lt;Tabbar
  tabSwitch={<span class="hljs-function">(<span class="hljs-params">child, idx</span>) =&gt;</span> {
    alert(idx)
  }}
&gt;
  <span class="xml"><span class="hljs-tag">&lt;<span class="hljs-name">TabbarItem</span> <span class="hljs-attr">tabTitle</span>=<span class="hljs-string">&quot;\u9996\u9875&quot;</span> <span class="hljs-attr">icon</span>=<span class="hljs-string">&quot;home&quot;</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name">TabbarItem</span>&gt;</span></span>
  <span class="xml"><span class="hljs-tag">&lt;<span class="hljs-name">TabbarItem</span> <span class="hljs-attr">tabTitle</span>=<span class="hljs-string">&quot;\u5206\u7C7B&quot;</span> <span class="hljs-attr">icon</span>=<span class="hljs-string">&quot;category&quot;</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name">TabbarItem</span>&gt;</span></span>
  <span class="xml"><span class="hljs-tag">&lt;<span class="hljs-name">TabbarItem</span> <span class="hljs-attr">tabTitle</span>=<span class="hljs-string">&quot;\u53D1\u73B0&quot;</span> <span class="hljs-attr">icon</span>=<span class="hljs-string">&quot;find&quot;</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name">TabbarItem</span>&gt;</span></span>
  <span class="xml"><span class="hljs-tag">&lt;<span class="hljs-name">TabbarItem</span> <span class="hljs-attr">tabTitle</span>=<span class="hljs-string">&quot;\u8D2D\u7269\u8F66&quot;</span> <span class="hljs-attr">icon</span>=<span class="hljs-string">&quot;cart&quot;</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name">TabbarItem</span>&gt;</span></span>
  <span class="xml"><span class="hljs-tag">&lt;<span class="hljs-name">TabbarItem</span> <span class="hljs-attr">tabTitle</span>=<span class="hljs-string">&quot;\u6211\u7684&quot;</span> <span class="hljs-attr">icon</span>=<span class="hljs-string">&quot;my&quot;</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name">TabbarItem</span>&gt;</span></span>
&lt;/Tabbar&gt;
</code></pre><h3>\u81EA\u5B9A\u4E49\u9009\u4E2D</h3><pre><code class="language-tsx">&lt;Tabbar visible={<span class="hljs-number">2</span>}&gt;
  <span class="xml"><span class="hljs-tag">&lt;<span class="hljs-name">TabbarItem</span> <span class="hljs-attr">tabTitle</span>=<span class="hljs-string">&quot;\u9996\u9875&quot;</span> <span class="hljs-attr">icon</span>=<span class="hljs-string">&quot;home&quot;</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name">TabbarItem</span>&gt;</span></span>
  <span class="xml"><span class="hljs-tag">&lt;<span class="hljs-name">TabbarItem</span> <span class="hljs-attr">tabTitle</span>=<span class="hljs-string">&quot;\u5206\u7C7B&quot;</span> <span class="hljs-attr">icon</span>=<span class="hljs-string">&quot;category&quot;</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name">TabbarItem</span>&gt;</span></span>
  <span class="xml"><span class="hljs-tag">&lt;<span class="hljs-name">TabbarItem</span> <span class="hljs-attr">tabTitle</span>=<span class="hljs-string">&quot;\u53D1\u73B0&quot;</span> <span class="hljs-attr">icon</span>=<span class="hljs-string">&quot;find&quot;</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name">TabbarItem</span>&gt;</span></span>
  <span class="xml"><span class="hljs-tag">&lt;<span class="hljs-name">TabbarItem</span> <span class="hljs-attr">tabTitle</span>=<span class="hljs-string">&quot;\u8D2D\u7269\u8F66&quot;</span> <span class="hljs-attr">icon</span>=<span class="hljs-string">&quot;cart&quot;</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name">TabbarItem</span>&gt;</span></span>
  <span class="xml"><span class="hljs-tag">&lt;<span class="hljs-name">TabbarItem</span> <span class="hljs-attr">tabTitle</span>=<span class="hljs-string">&quot;\u6211\u7684&quot;</span> <span class="hljs-attr">icon</span>=<span class="hljs-string">&quot;my&quot;</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name">TabbarItem</span>&gt;</span></span>
&lt;/Tabbar&gt;
</code></pre><h3>\u5FBD\u6807\u63D0\u793A</h3><pre><code class="language-tsx">&lt;Tabbar&gt;
  <span class="xml"><span class="hljs-tag">&lt;<span class="hljs-name">TabbarItem</span> <span class="hljs-attr">tabTitle</span>=<span class="hljs-string">&quot;\u9996\u9875&quot;</span> <span class="hljs-attr">icon</span>=<span class="hljs-string">&quot;home&quot;</span> <span class="hljs-attr">num</span>=<span class="hljs-string">&quot;11&quot;</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name">TabbarItem</span>&gt;</span></span>
  <span class="xml"><span class="hljs-tag">&lt;<span class="hljs-name">TabbarItem</span> <span class="hljs-attr">tabTitle</span>=<span class="hljs-string">&quot;\u5206\u7C7B&quot;</span> <span class="hljs-attr">icon</span>=<span class="hljs-string">&quot;category&quot;</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name">TabbarItem</span>&gt;</span></span>
  <span class="xml"><span class="hljs-tag">&lt;<span class="hljs-name">TabbarItem</span> <span class="hljs-attr">tabTitle</span>=<span class="hljs-string">&quot;\u53D1\u73B0&quot;</span> <span class="hljs-attr">icon</span>=<span class="hljs-string">&quot;find&quot;</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name">TabbarItem</span>&gt;</span></span>
  <span class="xml"><span class="hljs-tag">&lt;<span class="hljs-name">TabbarItem</span> <span class="hljs-attr">tabTitle</span>=<span class="hljs-string">&quot;\u8D2D\u7269\u8F66&quot;</span> <span class="hljs-attr">icon</span>=<span class="hljs-string">&quot;cart&quot;</span> <span class="hljs-attr">num</span>=<span class="hljs-string">&quot;110&quot;</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name">TabbarItem</span>&gt;</span></span>
  <span class="xml"><span class="hljs-tag">&lt;<span class="hljs-name">TabbarItem</span> <span class="hljs-attr">tabTitle</span>=<span class="hljs-string">&quot;\u6211\u7684&quot;</span> <span class="hljs-attr">icon</span>=<span class="hljs-string">&quot;my&quot;</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name">TabbarItem</span>&gt;</span></span>
&lt;/Tabbar&gt;
</code></pre><h3>\u81EA\u5B9A\u4E49\u989C\u8272</h3><pre><code class="language-tsx"> &lt;Tabbar unactiveColor=<span class="hljs-string">&quot;#7d7e80&quot;</span> activeColor=<span class="hljs-string">&quot;#1989fa&quot;</span>&gt;
  <span class="xml"><span class="hljs-tag">&lt;<span class="hljs-name">TabbarItem</span> <span class="hljs-attr">tabTitle</span>=<span class="hljs-string">&quot;\u9996\u9875&quot;</span> <span class="hljs-attr">icon</span>=<span class="hljs-string">&quot;home&quot;</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name">TabbarItem</span>&gt;</span></span>
  <span class="xml"><span class="hljs-tag">&lt;<span class="hljs-name">TabbarItem</span> <span class="hljs-attr">tabTitle</span>=<span class="hljs-string">&quot;\u5206\u7C7B&quot;</span> <span class="hljs-attr">icon</span>=<span class="hljs-string">&quot;category&quot;</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name">TabbarItem</span>&gt;</span></span>
  <span class="xml"><span class="hljs-tag">&lt;<span class="hljs-name">TabbarItem</span> <span class="hljs-attr">tabTitle</span>=<span class="hljs-string">&quot;\u53D1\u73B0&quot;</span> <span class="hljs-attr">icon</span>=<span class="hljs-string">&quot;find&quot;</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name">TabbarItem</span>&gt;</span></span>
  <span class="xml"><span class="hljs-tag">&lt;<span class="hljs-name">TabbarItem</span> <span class="hljs-attr">tabTitle</span>=<span class="hljs-string">&quot;\u8D2D\u7269\u8F66&quot;</span> <span class="hljs-attr">icon</span>=<span class="hljs-string">&quot;cart&quot;</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name">TabbarItem</span>&gt;</span></span>
  <span class="xml"><span class="hljs-tag">&lt;<span class="hljs-name">TabbarItem</span> <span class="hljs-attr">tabTitle</span>=<span class="hljs-string">&quot;\u6211\u7684&quot;</span> <span class="hljs-attr">icon</span>=<span class="hljs-string">&quot;my&quot;</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name">TabbarItem</span>&gt;</span></span>
&lt;/Tabbar&gt;
</code></pre><h3>\u4E09\u4E2Aicon\u7684tabbar</h3><pre><code class="language-tsx">&lt;Tabbar unactiveColor=<span class="hljs-string">&quot;#7d7e80&quot;</span> activeColor=<span class="hljs-string">&quot;#1989fa&quot;</span>&gt;
  <span class="xml"><span class="hljs-tag">&lt;<span class="hljs-name">TabbarItem</span> <span class="hljs-attr">tabTitle</span>=<span class="hljs-string">&quot;\u9996\u9875&quot;</span> <span class="hljs-attr">icon</span>=<span class="hljs-string">&quot;home&quot;</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name">TabbarItem</span>&gt;</span></span>
  <span class="xml"><span class="hljs-tag">&lt;<span class="hljs-name">TabbarItem</span> <span class="hljs-attr">tabTitle</span>=<span class="hljs-string">&quot;\u5206\u7C7B&quot;</span> <span class="hljs-attr">icon</span>=<span class="hljs-string">&quot;category&quot;</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name">TabbarItem</span>&gt;</span></span>
  <span class="xml"><span class="hljs-tag">&lt;<span class="hljs-name">TabbarItem</span> <span class="hljs-attr">tabTitle</span>=<span class="hljs-string">&quot;\u53D1\u73B0&quot;</span> <span class="hljs-attr">icon</span>=<span class="hljs-string">&quot;find&quot;</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name">TabbarItem</span>&gt;</span></span>
&lt;/Tabbar&gt;
</code></pre><h3>\u56FA\u5B9A\u5E95\u90E8\uFF0C\u53EF\u81EA\u7531\u8DF3\u8F6C</h3><pre><code class="language-tsx">&lt;Tabbar bottom={<span class="hljs-literal">true</span>}&gt;
  <span class="xml"><span class="hljs-tag">&lt;<span class="hljs-name">TabbarItem</span> <span class="hljs-attr">tabTitle</span>=<span class="hljs-string">&quot;\u9996\u9875&quot;</span> <span class="hljs-attr">href</span>=<span class="hljs-string">&quot;&quot;</span> <span class="hljs-attr">icon</span>=<span class="hljs-string">&quot;home&quot;</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name">TabbarItem</span>&gt;</span></span>
  <span class="xml"><span class="hljs-tag">&lt;<span class="hljs-name">TabbarItem</span> <span class="hljs-attr">tabTitle</span>=<span class="hljs-string">&quot;\u5206\u7C7B&quot;</span> <span class="hljs-attr">icon</span>=<span class="hljs-string">&quot;category&quot;</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name">TabbarItem</span>&gt;</span></span>
  <span class="xml"><span class="hljs-tag">&lt;<span class="hljs-name">TabbarItem</span> <span class="hljs-attr">tabTitle</span>=<span class="hljs-string">&quot;\u53D1\u73B0&quot;</span> <span class="hljs-attr">icon</span>=<span class="hljs-string">&quot;find&quot;</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name">TabbarItem</span>&gt;</span></span>
  <span class="xml"><span class="hljs-tag">&lt;<span class="hljs-name">TabbarItem</span> <span class="hljs-attr">tabTitle</span>=<span class="hljs-string">&quot;\u8D2D\u7269\u8F66&quot;</span> <span class="hljs-attr">href</span>=<span class="hljs-string">&quot;https://m.jd.com&quot;</span> <span class="hljs-attr">icon</span>=<span class="hljs-string">&quot;cart&quot;</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name">TabbarItem</span>&gt;</span></span>
  <span class="xml"><span class="hljs-tag">&lt;<span class="hljs-name">TabbarItem</span> <span class="hljs-attr">tabTitle</span>=<span class="hljs-string">&quot;\u6211\u7684&quot;</span> <span class="hljs-attr">href</span>=<span class="hljs-string">&quot;######&quot;</span> <span class="hljs-attr">icon</span>=<span class="hljs-string">&quot;my&quot;</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name">TabbarItem</span>&gt;</span></span>
&lt;/Tabbar&gt;
</code></pre><h2>API</h2><h3>Prop</h3><h3>nut-tabbar</h3><table><thead><tr><th>\u5B57\u6BB5</th><th>\u8BF4\u660E</th><th>\u7C7B\u578B</th><th>\u9ED8\u8BA4\u503C</th></tr></thead><tbody><tr><td>visible</td><td>\u9009\u4E2D\u6807\u7B7E\u7684\u7D22\u5F15\u503C</td><td>number</td><td>0</td></tr><tr><td>bottom</td><td>\u662F\u5426\u56FA\u5B9A\u5728\u9875\u9762\u5E95\u90E8</td><td>Booble</td><td>false</td></tr><tr><td>unactiveColor</td><td>icon\u672A\u6FC0\u6D3B\u7684\u989C\u8272</td><td>string</td><td>#7d7e80</td></tr><tr><td>activeColor</td><td>icon\u6FC0\u6D3B\u7684\u989C\u8272</td><td>string</td><td>#1989fa</td></tr></tbody></table><h3>tabbar-item</h3><table><thead><tr><th>\u5B57\u6BB5</th><th>\u8BF4\u660E</th><th>\u7C7B\u578B</th><th>\u9ED8\u8BA4\u503C</th></tr></thead><tbody><tr><td>tabTitle</td><td>\u6807\u7B7E\u9875\u7684\u6807\u9898</td><td>String</td><td>\u2013</td></tr><tr><td>icon</td><td>\u6807\u7B7E\u9875\u663E\u793A\u7684<a href="#/icon">\u56FE\u6807\u540D\u79F0</a> \u6216\u56FE\u7247\u94FE\u63A5</td><td>String</td><td>\u2013</td></tr><tr><td>href</td><td>\u6807\u7B7E\u9875\u7684\u8DF3\u8F6C\u94FE\u63A5</td><td>String</td><td>\u2013</td></tr><tr><td>num</td><td>\u9875\u7B7E\u53F3\u4E0A\u89D2\u7684\u6570\u5B57\u89D2\u6807\uFF0C\u8D85\u51FA99\u4E4B\u540E\u4E3A99+</td><td>Number</td><td>\u2013</td></tr></tbody></table><h3>Event</h3><table><thead><tr><th>\u4E8B\u4EF6\u540D\u79F0</th><th>\u8BF4\u660E</th><th>\u56DE\u8C03\u53C2\u6570</th></tr></thead><tbody><tr><td>tabSwitch</td><td>\u5207\u6362\u9875\u7B7E\u65F6\u89E6\u53D1\u4E8B\u4EF6</td><td>\u70B9\u51FB\u7684\u6570\u636E\u548C\u7D22\u5F15\u503C</td></tr></tbody></table>`,26),c=[p],g={setup(h,{expose:s}){return s({frontmatter:{}}),(e,j)=>(t(),a("div",l,c))}};export{g as default};
